# Generated by Django 5.0.7 on 2024-07-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
