# Generated by Django 5.0.7 on 2024-08-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myapp_published_date_alter_myapp_is_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Myapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myapp')),
            ],
        ),
    ]
